### ISSUE TITLE
The caller does not have permission

### ISSUE THREAD

**Issue by drifteaur** [internetztube/craft-spreadsheet-translations#1]
Hello! Your plugin looks quite useful.

I've followed your instructions to set up a service account and the spreadsheet, but I'm getting the following error message when clicking "Test credentials" - any ideas?

It's a GSuite account, if it makes any difference.

```
Error!
{ "error": { "code": 403, "message": "The caller does not have permission", "errors": [ { "message": "The caller does not have permission", "domain": "global", "reason": "forbidden" } ], "status": "PERMISSION_DENIED" } }
Class: Google_Service_Exception
```

**Comment by internetztube** [comment]
Hi @drifteaur!
Thanks for your feedback. I really appreciate it!

Did you share the spreadsheet with the eMail from the service account?

**Comment by internetztube** [comment]
Closed due to inactivity.
