### ISSUE TITLE
Will this work with multiple translation files?

### ISSUE THREAD

**Issue by thijskaspers** [internetztube/craft-spreadsheet-translations#2]
The default translations are stored in site.php, but will this also work when you have more translation files?

In `config/app.php` we have defined more translation files through the `i18n` setting like so:

````
return [
    'modules' => [
        'my-module' => \modules\Module::class,
    ],
    'components' => [
        'i18n' => [
            'translations' => [
                'stock' => [
                    'class' => craft\i18n\PhpMessageSource::class,
                    'sourceLanguage' => 'en',
                    'basePath' => dirname(__DIR__) . '/translations',
                    'allowOverrides' => true,
                ],
            ],
        ],
    ],
];
````

Will the plugin be smart enough to know in which files the translations have to be stored when we do a pull?

**Comment by internetztube** [comment]
The plugin just translates the `site.php` in each language folder.
I will add that feature this week.

**Comment by thijskaspers** [comment]
Thanks! Will also come in handy for plugins like Formie, they separate the translations into formie.php, so "First name" in formie.php can be translated differently than "First name" in site.php if you want.

We are testing the plugin with a client on a staging server, and so far it's great :) especially since all translations are pulled into the PHP files (instead of the database) and we can commit them.

One minor thingy, would be cool if the name can be changed in the sidebar, current name is too long:
![Schermafbeelding 2021-02-12 om 11 13 31](https://user-images.githubusercontent.com/1608184/107755623-5dce0d80-6d23-11eb-8d1d-0e8c89af64ae.png)

**Comment by internetztube** [comment]
Thanks for your feature request.
https://github.com/internetztube/craft-spreadsheet-translations/releases/tag/1.1.1

```
composer update internetztube/craft-spreadsheet-translations
```
